[WIP] Integrate test suite with GitHub Actions
test-org-dm/docker-mailserver pull request #2
Opened 2020-12-05 15:48 UTC by radicand

This is a WIP for integrated CI in GitHub Actions. Do not yet merge.

2020-12-09 19:19 UTC, martin-schulze-vireso requested changes

2020-12-09 19:19 UTC, martin-schulze-vireso commented on test/test_helper/common.bash
> +# NAME=tvial/docker-mailserver:testing
Commenting this out might have bad sideeffects with the change `IMAGE_NAME=${NAME}` in `setup.sh` above.

2020-12-09 19:19 UTC, martin-schulze-vireso commented on setup.sh
> +      IMAGE_NAME=${NAME}
Better to use `${NAME?}` here, to fail early and loud.

2020-12-09 19:22 UTC, radicand commented on test/test_helper/common.bash
> +# NAME=tvial/docker-mailserver:testing
it's not obvious, but NAME is seeded in the env in the GHA pipeline (https://github.com/test-org-dm/docker-mailserver/blob/gha/test-suite/.github/workflows/build_test_push.yml#L101)

2020-12-09 19:23 UTC, radicand commented on setup.sh
> +      IMAGE_NAME=${NAME}
Worth a change to look at, again per comment above, NAME should always be present

2020-12-09 20:35 UTC, martin-schulze-vireso commented on test/test_helper/common.bash
> +# NAME=tvial/docker-mailserver:testing
That is okay for CI but doesn't that hamper local development? We now need to set up `$NAME` manually, which is prone to errors like forgetting to do so or typos.

2020-12-09 20:41 UTC, radicand commented on test/test_helper/common.bash
> +# NAME=tvial/docker-mailserver:testing
This is a valid point in that we should have some sort of fallback default. I'll see what our options are here.

2020-12-09 21:47 UTC, williamdes commented on setup.sh
> +      IMAGE_NAME=${NAME}
```suggestion
      IMAGE_NAME=${NAME:-tvial/docker-mailserver:latest}
```

2020-12-09 21:54 UTC, martin-schulze-vireso commented on setup.sh
> +      IMAGE_NAME=${NAME}
@williamdes I am not sure if the default value should be set at this depth. Come to think of it, I am not even sure if `NAME` should be used as an interface here, that will spell trouble somewhere down the line due to name clashes.

2020-12-12 14:42 UTC, radicand commented on test/test_helper/common.bash
> +# NAME=tvial/docker-mailserver:testing
I've updated this to fallback as discussed.

2020-12-12 14:45 UTC, radicand commented on setup.sh
> +      IMAGE_NAME=${NAME}
I did end up changing as @williamdes suggested, if it reaches that far into the execution without NAME set, it does either need a default value or to bomb. Again, open to suggestions.

2020-12-12 16:06 UTC, williamdes approved these changes

2020-12-23 22:07 UTC, williamdes commented on .github/workflows/build_test_push.yml
> +          sudo wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJ
I was about to create a shellcheck github action, do you want me to proceed ?

2020-12-23 22:17 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          sudo wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJ
I don't have strong preferences, I'm just mimicking what the existing build process does; if there's an action driven way that works with the existing lint.sh script, go for it.

2020-12-24 01:46 UTC, radicand commented
I've completed the MVP for lint>build>test>publish, marking this ready for review now.

2020-12-24 02:43 UTC, williamdes commented on .github/workflows/build_test_push.yml
> +name: CI-WIP
```suggestion
name: Build, test and push
```

2020-12-24 02:44 UTC, williamdes commented on .github/workflows/build_test_push.yml
> +          sudo wget -qO- "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/${ECLINT_VERSION}/ec-linux-amd64.tar.gz" | tar -xaz
you could use curl here and above to be consistent with HADOLINT ?

2020-12-24 02:45 UTC, williamdes approved these changes

2020-12-26 21:16 UTC, williamdes commented on .github/workflows/build_test_push.yml
> +          sudo wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJ
Here it is https://github.com/sudo-bot/action-shellcheck#readme
enjoy !
I added make and bash for you ;)

2021-01-02 10:46 UTC, aendeavor commented
Nice! There are some comments left that need resolving, but all in all, this looks superb! I will now go ahead back to the main repo and start the migration process so we all can enjoy the new testing system.

@radicand and @williamdes thank you very much for your work here. We will make sure this is honored in the new repository!

2021-01-04 17:58 UTC, radicand commented
Just updated to remove WIP.

2021-01-04 18:02 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          sudo wget -qO- "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/${ECLINT_VERSION}/ec-linux-amd64.tar.gz" | tar -xaz
Just made this change to be consistently

2021-01-04 18:06 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          sudo wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJ
Just noting that this is something to re-visit later - as noted, the linter currently uses a custom lint.sh script to manage the linting process, we'd need to ensure the action method works the same way (or accomplished the same outcomes). It's not a blocker to merge, more of an enhancement IMO.

2021-01-04 18:44 UTC, aendeavor approved these changes

2021-01-04 18:45 UTC, merged